language: php
services:
  - mysql
php:
  - "7.2"

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testing;'
  - sudo mysql_upgrade -u root -proot
  - sudo service mysql restart
before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit

